[input]
base_directory = "/Users/loparcog/Documents/Projects/loparcog.github.io"
html_selector = "main"

[[input.files]]
path = "mostly-complete-dogument.html"
url = "/mostly-complete-dogument.html"
title = "Mostly Complete Dogument"

[[input.files]]
path = "tester.html"
url = "/tester.html"
title = "Tester"