[input]
base_directory = "/Users/loparcog/Documents/Projects/loparcog.github.io"
html_selector = "main"

[[input.files]]
path = "my-first-review.html"
url = "/my-first-review.html"
title = "My First Review"